In [1]:
import numpy as np
import statistics
from statistics import mode
import os

In [11]:
os.chdir('/Users/shubhampatel/Desktop/PRML/Assignment 3/Data/Isolated Digits')


In [2]:
def DTW(x, y):
	m = x.shape[0]+1
	n = y.shape[0]+1
	dtw = np.ones((m, n)) * np.inf
	dtw[0,0] = 0
	
	for i in range(1,m):
		for j in range(1,n):
			cost = np.linalg.norm(x[i-1, :] - y[j-1, :])
			penalty = np.array([dtw[i-1, j-1], dtw[i-1, j], dtw[i, j-1]])
			dtw[i, j] = penalty.min() + cost

	return dtw

In [3]:
def read_data(dataset, type, filetype):
	curr = os.getcwd()
	path = f"{curr}/{dataset}/{type}"
	os.chdir(path)

	dataList = []
	files = [file for file in os.listdir() if file.endswith(filetype)]

	for file in files:
		dataList.append(np.genfromtxt(file, delimiter=' ', skip_header=1, dtype=float))
	os.chdir(curr)
	return dataList

In [12]:
train_2 = read_data('2', 'train', '.mfcc')
dev_2 = read_data('2', 'dev', '.mfcc')
train_3 = read_data('3', 'train', '.mfcc')
dev_3 = read_data('3', 'dev', '.mfcc')
train_4 = read_data('4', 'train', '.mfcc')
dev_4 = read_data('4', 'dev', '.mfcc')
train_5 = read_data('5', 'train', '.mfcc')
dev_5 = read_data('5', 'dev', '.mfcc')
train_z = read_data('z', 'train', '.mfcc')
dev_z = read_data('z', 'dev', '.mfcc')

In [13]:
C = 25

class_2 = []
class_3 = []
class_4 = []
class_5 = []
class_z = []

In [14]:
for dev in dev_2:
	cost = []
	for train in train_2:
		cost.append([DTW(dev,train)[-1,-1], 1])
	for train in train_3:
		cost.append([DTW(dev,train)[-1,-1], 2])
	for train in train_4:
		cost.append([DTW(dev,train)[-1,-1], 3])
	for train in train_5:
		cost.append([DTW(dev,train)[-1,-1], 4])
	for train in train_z:
		cost.append([DTW(dev,train)[-1,-1], 5])
	cost = np.array(cost)
	idx = cost[:,0].argsort()
	cost = cost[idx]
	class_2.append(mode(cost.reshape(-1,2)[:C,1]))

In [ ]:
print(class_2)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [ ]:
for dev in dev_3:
	cost = []
	for train in train_2:
		cost.append([DTW(dev,train)[-1,-1], 1])
	for train in train_3:
		cost.append([DTW(dev,train)[-1,-1], 2])
	for train in train_4:
		cost.append([DTW(dev,train)[-1,-1], 3])
	for train in train_5:
		cost.append([DTW(dev,train)[-1,-1], 4])
	for train in train_z:
		cost.append([DTW(dev,train)[-1,-1], 5])
	cost = np.array(cost)
	idx = cost[:,0].argsort()
	cost = cost[idx]
	class_3.append(mode(cost.reshape(-1,2)[:C,1]))

In [ ]:
print(class_3)

[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0]


In [ ]:
for dev in dev_4:
	cost = []
	for train in train_2:
		cost.append([DTW(dev,train)[-1,-1], 1])
	for train in train_3:
		cost.append([DTW(dev,train)[-1,-1], 2])
	for train in train_4:
		cost.append([DTW(dev,train)[-1,-1], 3])
	for train in train_5:
		cost.append([DTW(dev,train)[-1,-1], 4])
	for train in train_z:
		cost.append([DTW(dev,train)[-1,-1], 5])
	cost = np.array(cost)
	idx = cost[:,0].argsort()
	cost = cost[idx]
	class_4.append(mode(cost.reshape(-1,2)[:C,1]))

In [ ]:
print(class_4)

[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]


In [ ]:
for dev in dev_5:
	cost = []
	for train in train_2:
		cost.append([DTW(dev,train)[-1,-1], 1])
	for train in train_3:
		cost.append([DTW(dev,train)[-1,-1], 2])
	for train in train_4:
		cost.append([DTW(dev,train)[-1,-1], 3])
	for train in train_5:
		cost.append([DTW(dev,train)[-1,-1], 4])
	for train in train_z:
		cost.append([DTW(dev,train)[-1,-1], 5])
	cost = np.array(cost)
	idx = cost[:,0].argsort()
	cost = cost[idx]
	class_5.append(mode(cost.reshape(-1,2)[:C,1]))

In [ ]:
print(class_5)

[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.0]


In [ ]:
for dev in dev_z:
	cost = []
	for train in train_2:
		cost.append([DTW(dev,train)[-1,-1], 1])
	for train in train_3:
		cost.append([DTW(dev,train)[-1,-1], 2])
	for train in train_4:
		cost.append([DTW(dev,train)[-1,-1], 3])
	for train in train_5:
		cost.append([DTW(dev,train)[-1,-1], 4])
	for train in train_z:
		cost.append([DTW(dev,train)[-1,-1], 5])
	cost = np.array(cost)
	idx = cost[:,0].argsort()
	cost = cost[idx]
	class_z.append(mode(cost.reshape(-1,2)[:C,1]))

In [ ]:
print(class_z)
temp = np.array(class_z)

[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 5.0, 5.0]
11


In [ ]:
CMatrix = np.zeros((5,5))
a = []

for i in range(1,6):
  a.append(class_2.count(i))
CMatrix[0] = a
a = []
for i in range(1,6):
  a.append(class_3.count(i))
CMatrix[1] = a
a = []
for i in range(1,6):
  a.append(class_4.count(i))
CMatrix[2] = a
a = []
for i in range(1,6):
  a.append(class_5.count(i))
CMatrix[3] = a
a = []
for i in range(1,6):
  a.append(class_z.count(i))
CMatrix[4] = a
print(CMatrix)



[[12.  0.  0.  0.  0.]
 [ 1. 11.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  1. 11.  0.]
 [ 1.  0.  0.  0. 11.]]
